var img;
var high;
var low;
var forward;
var back;
var left;
var right;
var digi0;
var digi1;
var digi2;
var digi3;
var digi4;
var digi5;
var digi6;
var digi7;
var digi8;
var digi9;
var new0;
var new1;
var new2;
var new3;
var new4;
var new5;
var new6;
var new7;
var new8;
var new9;

function setup() {
    createCanvas(window.innerWidth,window.innerHeight);
    img = loadImage('https://i.imgur.com/0B11mBw.jpg');
    high = loadImage('https://i.imgur.com/Achclh4.jpg');
    low = loadImage('https://i.imgur.com/48bSU7T.jpg');
    forward = loadImage('https://i.imgur.com/9ycK4ry.jpg');
    back = loadImage('https://i.imgur.com/TMNLuha.jpg');
    left = loadImage('https://i.imgur.com/WtWta5X.jpg');
    right = loadImage('https://i.imgur.com/jDEx7jo.jpg');
    digi0 = loadImage('https://i.imgur.com/FGGGtKm.jpg');
    digi1 = loadImage('https://i.imgur.com/seMhuJW.jpg');
    digi2 = loadImage('https://i.imgur.com/FAIS6gP.jpg');
    digi3 = loadImage('https://i.imgur.com/IZL1sb1.jpg');
    digi4 = loadImage('https://i.imgur.com/R5kiVeX.jpg');
    digi5 = loadImage('https://i.imgur.com/JYrJSfq.jpg');
    digi6 = loadImage('https://i.imgur.com/BW2HhMZ.jpg');
    digi7 = loadImage('https://i.imgur.com/dYOGB0V.jpg');
    digi8 = loadImage('https://i.imgur.com/GFbM3Wc.jpg');
    digi9 = loadImage('https://i.imgur.com/QyHfLgg.jpg');
    new0 = loadImage('https://i.imgur.com/UqdY0CA.png');
    new1 = loadImage('https://i.imgur.com/LcFK3Ma.png');
    new2 = loadImage('https://i.imgur.com/X7FLtfI.png');
    new3 = loadImage('https://i.imgur.com/ZC6joUM.png');
    new4 = loadImage('https://i.imgur.com/MGwji5Y.png');
    new5 = loadImage('https://i.imgur.com/sbctn5q.png');
    new6 = loadImage('https://i.imgur.com/i2JHbXE.png');
    new7 = loadImage('https://i.imgur.com/urVwNT5.png');
    new8 = loadImage('https://i.imgur.com/CtHyGLn.png');
    new9 = loadImage('https://i.imgur.com/yNI2c8v.png');

}